name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  regression_tests:
    name: k8s regression tests
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # knative support has been deprecated: https://github.com/solo-io/gloo/issues/5707
        # We have removed it from our CI regression tests
        kube-e2e-test-type: ['gateway', 'ingress', 'helm', 'gloomtls', 'glooctl']
        xds-relay: [ 'false' ]
        include:
          - kube-e2e-test-type: 'gateway'
            xds-relay: 'true'
    steps:
    - name: Cancel Previous Actions
      uses: styfle/cancel-workflow-action@0.4.1
      with:
        access_token: ${{ github.token }}
    - name: Free disk space
      run: |
        echo "Before clearing disk space:"
        df -h

        # https://github.com/actions/virtual-environments/issues/709
        sudo apt-get clean

        # Clean up pre-installed tools
        # https://github.com/actions/virtual-environments/issues/1918
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf $AGENT_TOOLSDIRECTORY

        echo "After clearing disk space:"
        df -h
    - name: Set up Go 1.16.3
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: engineerd/setup-kind@v0.5.0
      with:
        # We rely on the `deploy-to-kind-cluster` script to create a kind cluster
        skipClusterCreation: true
        version: v0.11.1
    - uses: azure/setup-kubectl@v1
      id: kubectl
      with:
        version: 'v1.22.4'
    - uses: azure/setup-helm@v1
      with:
        version: v3.6.3
    - name: Setup test env
      env:
        KUBE2E_TESTS: ${{ matrix.kube-e2e-test-type }}
        USE_XDS_RELAY: ${{ matrix.xds-relay }}
        CLUSTER_NAME: 'kind'
        CLUSTER_NODE_VERSION: 'v1.22.4@sha256:ca3587e6e545a96c07bf82e2c46503d9ef86fc704f44c17577fca7bcabf5f978'
        VERSION: '0.0.0-kind'
      run: |
        ./ci/deploy-to-kind-cluster.sh
    - name: Testing - kube e2e regression tests
      env:
        KUBE2E_TESTS: ${{ matrix.kube-e2e-test-type }}
        ACK_GINKGO_RC: true
        ACK_GINKGO_DEPRECATIONS: 1.16.5
      run: |
        make run-ci-regression-tests
    - uses: testspace-com/setup-testspace@v1
      with:
        domain: solo-io.testspace.com
      if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    - name: Push result to Testspace server
      run: |
        testspace push --verbose "**/junit.xml"
      if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    - name: Debug Info
      if: failure()
      run: |
        # see what's in the cluster if we failed
        kubectl get all -A
        kubectl get configmaps -A
    - name: Set pull_request_url
      if: ${{ github.event_name == 'pull_request' && failure() }}
      run: echo "pull_request_url=$(cat ${{ github.event_path }} | jq --raw-output .pull_request._links.html.href)" >> $GITHUB_ENV
    - name: Set direct_message_id
      if: ${{ github.event_name == 'pull_request' && failure() }}
      run: echo "direct_message_id=$(cat ./.github/workflows/notify-on-regression-failure-list.json | jq -r '."${{ github.actor }}"')" >> $GITHUB_ENV
    - name: Send Message
      id: message-on-fail
      if: ${{ github.event_name == 'pull_request' && failure() }}
      shell: bash
      run: |
        curl -X POST https://slack.com/api/chat.postMessage\
              -H "Content-Type: application/json; charset=utf-8"\
              -H "Authorization: Bearer ${{ secrets.SLACKBOT_BEARER }}"\
              -d '{"channel":"${{ env.direct_message_id }}","text":"Hey, `${{ github.actor }}`!  The <https://github.com/solo-io/gloo/actions/runs/${{github.run_id}}|regression tests> for your <${{ env.pull_request_url }}|${{ github.head_ref }} PR> have failed."}'
